### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#105]
Do you have plans to support asyncio in ROM?

For example, by integrating [aioredis](https://github.com/aio-libs/aioredis)?

**Comment by josiahcarlson** [comment]
I have no current plans to integrate async support into rom. This is mostly because I am not using asyncio, and because *proper* integration would radically alter quite a few things in the library, making rom Python 3.x-only. Being that I am getting paid to run rom in 2.x, it's actually against my interest to do *any* development towards asyncio integration. There are a few ways around the biggest changes, but again, I'm not using asyncio anywhere - and wouldn't even if I needed 3.x asynchronous IO; there are several better libraries already.

If you want to pay me to add this, contact me off-list with what you are willing to pay, and I'll tell you my answer. In the mean time, based on our previous interactions, I'm going to assume you're not interested in paying enough to make this happen from my side, so I'll close this. If I'm wrong, I'll reopen.
