### ISSUE TITLE
Feature request: binary columns

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#111]
I would like to be able to store binary data (bytes) in a column. Perhaps due to use of Lua, it seems like ROM wants string data for all columns.

This came up because I wanted to compress the data behind a JSON-type column I've made.

**Comment by josiahcarlson** [comment]
There should be no issues with round-tripping binary data, but it's awkward because *Python* and *Redis* independently do weird things.

The tests aren't great, but https://github.com/josiahcarlson/rom/blob/master/test/test_rom.py#L1422 shows binary round-tripping in Python 3.x and Python 2.x using the `rom.String` column.

If you want to compress json data before storing it in the column, you can look into how rom round-trips binary string data, then just do your conversions before/after that binary is round-tripped.
