### ISSUE TITLE
Testing code for column primitive types and indexes

### ISSUE THREAD

**Issue by healiseu** [josiahcarlson/rom#124]
Hi Josiah, I have started testing your ROM project. I think you have done a great job and I am really interested in finding out how to leverage its use in TRIADB project. Hopefully that will open a new window for your project to joins and hypergraphs. 

First I started testing the primitive attribute types of ROM model. For this purpose you may download my [jupyter notebook][2] from the [library I created for your project][1] at Microsoft Azure notebooks cloud. 

#### Q1. Can you explain the phrase "forgets all known entities in the session"
You may see the object addresses when I created them. Then I executed a `session.commit()` and run a `query.all()`. The object addresses of the result set were the **same with those at creation time**. Then I executed a `session.rollback` and repeated the `query.all` and **this time the object addresses are different**. I have also noticed with [redis Commander management tool][3] that every time query.all is executed a ZSET of pid(s) is created with a timeout. Documentation on both `util.Session.commit` and `util.Session.rollback` method. says that **forgets all known entities in the session**. Can you explain what exactly is going on behind the scenes referencing my testing example. 

#### Q2. Which column type do you use for raw binary data ?
Suppose you want to save images, what column type will you use. Do you consider that to be a limitation of the current ROM version ?

#### Q3. What kind of indexing you declare for different attribute types ?
In TRIADB primitive types are defined in a similar manner to universal data element concepts (see [UDEF][4] and [CCTS][5]). For example there are 5 different Text types, one for long text, another of unique ids, e.g. SSNs, another for enumerated types, another for short length strings, e.g. names, and another for URL. What strategy one should follow to cope with these in terms of keygen, unique and prefix parameters. What would you recommend for the current example to make it more interesting.

#### Q4. What is this big hash table doing behind the scene ?
I examined the structure that ROM creates on REDIS database using [redis Commander management tool][3] and I discovered that you create a hash with key `RomColumns::`. that contains for each record id a list value. Part of the content in this list is ["pid","pd","pdt","preal","pint"]. This is repeated for all 10 records. And there are many other **long** lists for the text columns including empy lists. What is this ? Whatever its use, it will grow a lot with many records and it seems to me that it is inefficient at least because repeated lists are eating a lot of memory space.

I will fire more questions when I execute queries on another jupyter notebook. Hope you can really bear with me. 

Thank you in advance for your answers to my questions

PS: You may create some space at Github for jupyter notebooks that demonstrate ROM. I will be more than happy to contribute my work there. Please do let me know. 

[1]: https://notebooks.azure.com/athanassios/libraries/redisrom
[2]: https://redisrom-athanassios.notebooks.azure.com/nb/notebooks/ROM%20-%20Testing%20column%20types%20and%20indexes.ipynb
[3]: https://github.com/joeferner/redis-commander
[4]: https://en.wikipedia.org/wiki/Universal_Data_Element_Framework
[5]: https://www.unece.org/cefact/codesfortrade/ccts_datatypecatalogue.html

**Comment by josiahcarlson** [comment]
> You may see the object addresses when I created them. Then I executed a session.commit() and run a query.all(). The object addresses of the result set were the same with those at creation time. Then I executed a session.rollback and repeated the query.all and this time the object addresses are different.

The `session` is just a cache of data that you have recently used. Rom was meant as a Redis-backed alternative to SqlAlchemy / Django ORM, so the `session` was meant to hold data involved in a single web request / response cycle. A `.commit()` ensures that data is saved back to Redis (we keep weak references to the data, just in case you re-request the same data after `.commit()`, even in a different web request, and because you have a list of those objects hanging around, the original objects are never freed). A `.rollback()` makes sure that we're not keeping any cache, because we clear all of our references.

If you would like to disable this behavior, see the relevant docs on the "null session" and the "rom session":
https://josiahcarlson.github.io/rom/util.html#using-a-non-caching-session-object
https://josiahcarlson.github.io/rom/util.html#rom.util.use_null_session
https://josiahcarlson.github.io/rom/util.html#rom.util.use_rom_session

> I have also noticed with redis Commander management tool that every time query.all is executed a ZSET of pid(s) is created with a timeout. Documentation on both util.Session.commit and util.Session.rollback method. says that forgets all known entities in the session. Can you explain what exactly is going on behind the scenes referencing my testing example.

All queries that pass through the `Model.query` interface needs working space for in-progress and already-done queries. These come in the form of uuid-named keys, which are either sets or sorted sets (depending on the query), and are stored in Redis with an expiration that is refreshed during query result pagination (assuming you're processing items fast enough). If you just need to scan through numeric indexes, and know the starting / ending points, you can use `Model.get_by(attr=(start, end), _limit=(offset, count))`.:
https://josiahcarlson.github.io/rom/model.html#rom.model.Model.get_by

> Suppose you want to save images, what column type will you use. Do you consider that to be a limitation of the current ORM version ?

The `rom.String` column type should be binary-safe. It takes Python 2.7 str/bytes and Python 3.x+ bytes. We've got regression tests to ensure that it can handle a variety of binary data. Over the wire during save / load, data is passed through a layer of json and possible unicode encodings / decodings, so there can be some performance overhead, but data-wise, it should round-trip just fine via rom.

> Generalizing indexing types according to column semantics

Indexes are generated based on whether you have provided `index`, `prefix`, `suffix, and/or `unique`, along with additional parameters like `keygen` or `keygen2`. It gets complicated. This is more or less me applying a bunch of ideas from several chapters of my book "Redis in Action", but much of it is from chapter 7. So if I can do something with a set intersection or union, that's what I do.

Long story short, `index / prefix / suffix` turns on non-unique indexing and `keygen` / `keygen2` are called to produce one of a few different things for further processing. The best place to check what happens based on what is called, is to look here to start: https://github.com/josiahcarlson/rom/blob/master/rom/model.py#L329

Depending on list/set/tuple vs. dictionary, we break into non-numeric vs. numeric indexes (generally), then put non-prefix/suffix indexes inside sets for fast intersection / union, prefix/suffix indexes inside sorted sets, and numeric indexes inside sorted sets.

> What strategy one should follow to cope with these in terms of keygen, unique and prefix parameters.

It depends on how you want to be able to find your data. I had a great talk on modeling and querying arbitrary data in Redis at Redisconf 2015 (which I gave again at Big Data Day LA 2015), but the videos are both down and I can't find them. The rom module mostly removes that, you just store your data in a natural way, then do your complicated stuff with your keygens...

If you've got "tags", storing them in a `rom.String` column with a `rom.FULL_TEXT` keygen will let you find entities using those tags in about as efficient a way as possible.

But if you've got an address book, you might want to set `prefix=True` and index on names and maybe a phonetic breakdown of the names (soundex, metaphone, etc.), then do one or more queries and combine the results.

The unique field is mostly to provide the ability for columns to be unique. Like if you've got a customer database with one field being `email`. Set `unique=True` for that column, make sure you normalize emails (lowercase your data), and now you'll get an exception if you try to save two different entities with the same email. This literally just uses a hash behind the scenes, and doesn't offer query support via `Model.query`. Some people use this functionality for their own custom "primary key", and in that sense, it works mostly like they would expect. For support inside `Model.query`, you need `index`, `prefix`, and/or `suffix` to be true.

The keygen generates data from your data to place into one or more indexes. The `keygen` argument takes the data for a column and returns the indexable data. The `keygen2` argument takes the column name, and a data dictionary for the entity, and allows you to combine multiple columns, pull data from a different column, etc., or even generate new data that only lives in the index. I use this on "empty" columns when I need to index one column in a few different ways that are otherwise incompatible with the individual column interface.

Numeric columns normally don't require an explicit keygen, while others (strings / text / json) do.

Geo indexes are completely separate, and are documented here:
https://josiahcarlson.github.io/rom/util.html#using-a-geo-index

> What would you recommend for the current example to make it more interesting.

There are at least a dozen examples in the `rom.column` and `rom.util` docs, along with a bunch more in the issue tracker here (open and closed) using various datatypes and indexes. With the `keygen2` argument, the types of data from the function, inverted indexes, prefix indexes, suffix indexes, pattern matching, etc., you can build basically any index you want; you just don't get custom result ordering unless you pre-calculate it in advance and store it explicitly.

> Big hash table behind the scenes ???

Long story short, Redis doesn't understand things like "foreign keys" or generally "dependent data". While we do as much as we can *inside* Redis, a lot of the logic for interacting with Redis, like generating data for indexes, etc., is done on the client. But because keygens / etc., can change on the client, and the client can "forget" about columns (old code, new code, etc.), we need to be able to delete data from indexes, even if our code changes on the client. In this case, that big key holds a bunch of index metadata, which is there to allow us to properly delete data from indexes when the main entity is deleted.

While there are other methods for *offline* index cleanup that don't necessarily involve having a big hash table, having that big hash table is terribly convenient and allows rom to (generally) operate without any big migrations, cleanups, or offline processes. The exception being when you need to add / replace / remove an index on an existing column with data, or if you want to delete a column.

Other *online* index cleanups need the equivalent of all of the data that's in the hash table key already, and about all that can be gained from that perspective is the distribution from a single large hash table key to a collection of smaller keys. This may offer some memory savings if we put this additional data in the hashes for individual entities, assuming that the memory limit for compact hashes in Redis isn't exceeded. This isn't impossible in the future, but due to the compatibility issues with the existing method, would require explicit enabling and may even require a data migration to fully clean out the old big hash.

I'm happy to answer your questions. But if possible, could you please try to stick to a single issue for your questions?

**Comment by josiahcarlson** [comment]
> In the future I will do try to break them in separate issues so other users and you can find it more convenient to reply.

That's kind-of the opposite of what I wanted, but my words were confusing.

Clarified: If you've got questions, please keep them to #124. If you've got bugs to report, feature requests, etc., please create a new issue.

> In the current issue regarding to my Q4 about ROM internal big hash table there can be a completely different logic to handle indexing.

Of course. There are a semi-infinite number of ways of indexing data. ;)

More to the point, I understand that there are other ways to do it, but this is currently the way rom does it. Not to say it couldn't change in the future, but there is a lot of data currently being stored in this format that would need to be migrated. Migrations are (relatively) expensive with rom.

> Now you may contrast ...

Indeed, that is a different way of storing data. Mechanically, I can't really replace rom's existing data storage methods without forcing a lot of people to do substantial migrations. And thinking about what data is stored where in this format vs rom, I'm not sure if any of the data would end up unchanged, except for primary key column values, and maybe indexes (which would be renamed).

Also (and again), because rom index data can be completely manufactured, and is commonly not the same as the column data, we always need a reference to a list of index keys that a given "row" generates, so we know how to clean it up. As stated before, this could be placed with row data, but is currently placed in a large hash.
