### ISSUE TITLE
void

### ISSUE THREAD

**Issue by healiseu** [josiahcarlson/rom#127]
Hi, in the following demo class

``` python
class MyClass(Model):

    dim3 = Integer(required=True)
    dim2 = Integer(required=True)
    dim1 = Integer(required=True)

    counter = Integer(required=True, default=0)

    def __repr__(self):
        return f'OBJ{self.id} ({self.dim3}, {self.dim2}, {self.dim1}) = {self.counter}'
```
I want to trigger an increment of the counter attribute based on some condition. For example:
``` python
obj100 = MyClass(dim3=1, dim2=0, dim1=0)
obj200 = MyClass(dim3=2, dim2=0, dim1=0)
obj300 = MyClass(dim3=3, dim2=0, dim1=0)

obj110 = MyClass(dim3=1, dim2=1, dim1=0)
```
How can I trigger an automatic increment of the counter for obj100  in ROM when the obj110 is created ?
Which is the fastest way to do such counter increment in ROM ? 
In model.py there are private methods such as `_after_insert()` does it make sense to override ?

PS: In the problem I am trying to solve, it would have been better if the primary index had been the triplet (dim3, dim2, dim1)

**Comment by healiseu** [comment]
sorry erase this issue, I could not describe it clearly...

**Comment by josiahcarlson** [comment]
I know you said to delete/erase, but there are some useful things in here for you:

If you need something to be unique together, see the documentation on `unique_together` in the docs: https://josiahcarlson.github.io/rom/model.html

If you need something calculated immediately before data insert/update, override `_before_insert` and/or `_before_update`. I use these when I need to keep an `updated_at` column for tracking changes, as well as generating "checksum" versions for uniqueness (hash the data instead of using the data itself, depending on data sizes).

To generating a mapping of unique 3-tuples to auto-generated numbers (maybe not exactly what you seemed to be after):

```
class MyModel(rom.Model):
    counter = rom.PrimaryKey()

    dim3 = Integer(required=True)
    dim2 = Integer(required=True)
    dim1 = Integer(required=True)

    unique_together = [('dim3', 'dim2', 'dim1')]

    def __repr__(self):
        return f'OBJ{self.id} ({self.dim3}, {self.dim2}, {self.dim1}) = {self.counter}'
```

Note that in this example, you can't change `counter`, it's just the value for this instance. 

If you are looking for something that allows you to directly change data in columns, rom doesn't support that internally, partly due to data consistency issues relating to indexes.

If you want to email me your questions, you can do that too.

**Comment by healiseu** [comment]
For the unique_together constrains and the composite order see my reply at #126
