### ISSUE TITLE
Indexed objects disappear from queries intermittently

### ISSUE THREAD

**Issue by EdgyEdgemond** [josiahcarlson/rom#131]
When updating an indexed object, queries using those indexes lose the item for a moment. This would appear to be due to the index being removed, and then added back in.

```
1540898063.567079 [0 lua] "HGET" "Peer:1" "id"
1540898063.567090 [0 lua] "HGET" "Peer:1" "heartbeat"
1540898063.567110 [0 lua] "HMSET" "Peer:1" "heartbeat" "1540898063.565095"
1540898063.567129 [0 lua] "HGET" "Peer::" "1"
1540898063.567144 [0 lua] "SREM" "Peer:protocol:http:idx" "1"
1540898063.567156 [0 lua] "SREM" "Peer:protocol:http:idx" "1"
1540898063.567169 [0 lua] "SREM" "Peer:role:validate:idx" "1"
1540898063.567180 [0 lua] "SREM" "Peer:role:validate:idx" "1"
1540898063.567193 [0 lua] "ZREM" "Peer:heartbeat:idx" "1"
1540898063.567204 [0 lua] "ZREM" "Peer:heartbeat:idx" "1"
1540898063.567217 [0 lua] "SADD" "Peer:protocol:http:idx" "1"
1540898063.567229 [0 lua] "SADD" "Peer:role:validate:idx" "1"
1540898063.567242 [0 lua] "ZADD" "Peer:heartbeat:idx" "1540898063.565095" "1"
1540898063.567272 [0 lua] "HSET" "Peer::" "1" "[[\"protocol:http\",\"role:validate\"],[\"heartbeat\"],{},{},{}]"
```

Is it possible to ensure atomicity of the update to prevent this issue?

**Comment by josiahcarlson** [comment]
I'm about 100% sure that you're misunderstanding the output of the Redis client in `MONITOR` mode. Specifically, every line that reads `[0 lua]` means that a Lua script is executing on db 0. To expand on that ...

rom uses Lua scripts for all index, un-index, and most query operations. And what you are seeing here is one Lua script call performing a series of operations inside that one call, via `MONITOR`. But again, because this is `MONITOR` output, you're getting commands *as they are run* directly from Redis. So, you get these individual commands (that said, the multiple delete calls seem unnecessary, so thank you for showing the output :) ).

But if you were to take a peek at the *replication stream*, what you would see is:
```
"MULTI"
"HMSET" "Peer:1" "heartbeat" "1540898063.565095"
"SREM" "Peer:protocol:http:idx" "1"
"SREM" "Peer:role:validate:idx" "1"
"ZREM" "Peer:heartbeat:idx" "1"
"SADD" "Peer:protocol:http:idx" "1"
"SADD" "Peer:role:validate:idx" "1"
"ZADD" "Peer:heartbeat:idx" "1540898063.565095" "1"
"HSET" "Peer::" "1" "[[\"protocol:http\",\"role:validate\"],[\"heartbeat\"],{},{},{}]"
"EXEC"
```

Because when Redis replicates Lua scripts using effects replication, it automatically wraps multiple commands with `MULTI`/`EXEC` before it heads to the replica, and only includes commands that change Redis (generally if `server.dirty` is incremented, but there are other cases). While you don't get the `MULTI`/`EXEC` in the `MONITOR` output because it was never called (as you notice), that doesn't matter, because the only stuff that can run during Lua script execution is generally informational, and/or related to killing Redis or the script (no read or write queries).

So yeah, what you think is a problem isn't actually a problem, because you aren't seeing what you think you're seeing, because Redis doesn't allow it. You can see what Redis expects by looking at the timing tests in the Redis repository as `tests/unit/scripting.tcl`.

Does this make sense?

**Comment by josiahcarlson** [comment]
One follow-up note: if you are replicating / executing directly from the `MONITOR` stream, you're going to have a *bad* time, because more than a few operations inside Redis explicitly replicate additional operations to replicas / AOF via the 'propagate / alsoPropagate` subsystem (that's how Lua gets `MULTI` and `EXEC` and sub-commands sent when `lua-replicate-commands` is enabled), but *do not* emit to `MONITOR`.

**Comment by EdgyEdgemond** [comment]
It makes sense in terms of Redis. Our bug however just gets more interesting based on this information.

We were checking the monitor stream to see if we could detect a cause to the strange behaviour.

Will continue investigating on our side. Thanks for the detailed response.

**Comment by josiahcarlson** [comment]
What version of Redis are you using? Which version of rom are you using? There may be a bug with the automatic sending of `MULTI`/`EXEC` in Redis, or maybe you're using a weird old version of rom?
