### ISSUE TITLE
rom breaks in python 3 if underlying Redis connection has decode_responses==True

### ISSUE THREAD

**Issue by mshalom-meta** [josiahcarlson/rom#147]
python3.6
redis==2.10.5
rom==1.0.0

`redis.Redis(..., decode_responses=True)` may be used in python3 to have the client decode the server byte responses into str.
Trouble is rom also tries to do the same in a couple of places so we end up with errors:
`AttributeError: 'str' object has no attribute 'decode'`

I'd suggest adding a helper somewhere (model.py? util.py?)
```
def _conn_needs_decoding(conn):
    return not conn.connection_pool.connection_kwargs['decode_responses']

```
Then, make the following change in `Model.refresh()` and `Model.get()`
```
-if six.PY3:
+if six.PY3 and _conn_needs_decoding(conn):
    data = dict((k.decode(), v.decode()) for k, v in data.items())

```
Also, in redis_writer_lua() you could remove:
```
-    if six.PY3:
-        result = result.decode()

```
since the `result = json.loads(result)` call in the next line works fine with either bytes or str as input

**Comment by josiahcarlson** [comment]
So, finally got a chance to look at this change. I like the change. Couldn't figure out how to use Github to set up a cross-fork PR, because it seems that your repo is not set up as a fork of my repo.

Looking through your changes, none of the line numbers in your change match up with line numbers in my PR. Looking at a manual diff between my master and your branch shows some missing upstream changes. Any particular reason?

Anyway, had to manually copy/paste changes to get them in, and they seem to work. Thank you for bug report. 1.0.1 tagged and uploaded as the fix.
