### ISSUE TITLE
Index for ManyToOne column

### ISSUE THREAD

**Issue by egalitarian** [josiahcarlson/rom#60]
Enabling indexing for ManyToOne columns allows filtering by the referenced model.

**Comment by josiahcarlson** [comment]
This is already enabled, available by default, and cannot be disabled. That is how OneToMany columns can return the list of entities that reference the base model.

You can use the automatic index with `.get_by()` and `.query.filter()` .

**Comment by josiahcarlson** [comment]
One small note about usage...

```
class TestA(Model):
    many = OneToMany('TestB', 'cascade', 'one')

class TestB(Model):
    one = ManyToOne('TestA')

# to find TestB entities referencing a given TestA entity:
ref = TestB.get_by(one=ent.id)
# or equivalently
ref = ent.many
```

**Comment by egalitarian** [comment]
Thanks, this should definitely be in the docs.

**Comment by josiahcarlson** [comment]
This was supposed to be in the docs, but due to the way I was specifying notes and warnings, 21 different notes and warnings didn't actually make it into the official docs. I have updated the way I add notes, have regenerated the docs, and now the note is available: https://pythonhosted.org/rom/rom.html#rom.ManyToOne

Still not perfect, but better :)
