### ISSUE TITLE
Limited Geo Support (new feature suggestion)

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#67]
A column type that stores 2d coordinates, and allows indexing and queries based on geohashes.

- would only support points and not any more complex shapes
- probably only 2d, but 3d might be easy to do at the same time
- should be possible to query based on a rectangle (range x/y) and center + radius (circle)
- [see this discussion](https://matt.sh/redis-geo#_how-it-works) on an approach for indexing
- [more, generalized, geo hashing code](https://code.google.com/p/python-geohash/)

I suspect most of the above could be accomplished with just a new "keygen" function and a new column type that packs/unpacks two numbers. However, to support new queries, I think more would be needed. If so, might be a good chance to generalize queries that a column type can support.

**Comment by josiahcarlson** [comment]
I will add Geo column and index support later, but not now. Why? Geo commands are already merged into Redis unstable, and are documented: http://redis.io/commands#geo . Rather than implementing geo support in Python + Lua (which is necessary for the way rom works), I'll wait for Geo support to get released in Redis. When I add Geo support, it is likely to only include point + radius queries, which is what the underlying geo primitives offer.

If you need Geo support now, or need it for older versions of Redis, email me offline to discuss your needs.

I will leave this issue open until a stable version of Redis is released with Geo support.

**Comment by peter-conalgo** [comment]
Cool! I didn't know this was coming in Redis. Makes sense to use it.

**Comment by LuisUrrutia** [comment]
Redis 3.2, which has geo support, is stable right now. 😃

**Comment by josiahcarlson** [comment]
Functionality available now in 0.37.0. Documentation here: https://pythonhosted.org/rom/rom.html#module-rom.util

Thanks for the ping Luis.
