### ISSUE TITLE
Unique together and/or exact strings

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#72]
Say I want to store documents, indexed by a "pathname" and update time. Typically would read only the latest version of each row, but they are there when you need the old versions.

````python
import rom, datetime

NOW = lambda: datetime.datetime.utcnow()

class Example(rom.Model):
    # a URL path; with slashes. 
    path = rom.String(index=True, keygen=rom.SIMPLE, prefix=True, unique=False, required=True)
    #path = rom.String(index=True, unique=True, required=True)

    # when it changed last
    as_of = rom.DateTime(index=True, required=True, default=NOW)

    unique_together = [ ('path', 'as_of') ]
    
    # ... etc ...
    value = rom.Integer()

    @classmethod
    def get_latest(cls, path):
        return cls.query.filter(path=path).order_by('-as_of').first()

if 1:
    rom.util.set_connection_settings(unix_socket_path='redis.sock')

    Example(path='abc', value = 1).save()
    Example(path='abc123', value = 2).save()
    Example(path='abc', value = 3).save()

    assert Example.get_latest('abc') != None
    assert Example.get_latest('abc').value == 3
````

Challenges:
- I cannot index a string for exact match. It wants a keygen function, but they aren't appropriate IMHO for this.
- `get_latest()` returns nothing, and I don't know why. (First assert fails.)
- random nit: the output from failed insert when duplicate value includes some binary (pickled data?). Would be nice to unpickle that.

I'm using your very latest, 0.32.2. I hope you don't mind all these issues, but it's refreshing to find a worthy project that's being actively developed!

**Comment by josiahcarlson** [comment]
This is something I don't need to patch rom to help you fix :)

Long story short, you need a new keygen function, and this is the keygen function you need:
```
def identity_keygen(st):
    return [st.strip()]
```
You won't be able to order by the path, but you will be able to pull by exact value on that column. Making that one change to the keygen function makes this work for me.

`SIMPLE` won't work for you as a keygen because it was meant to be for sorting by your string data, not necessarily searching for it.

Re: unique_together example with duplicates and binary exception:
Yeah, that is known and on purpose. Another long story short, I needed a method to take multiple columns of data and combine them in such a way that:
`(row1.col1, row1.col2) != (row2.col1, row2.col2)` -> `convert(row1.col1, row1.col2) != convert(row2.col1, row2.col2)`
and
`(row1.col1, row1.col2) == (row2.col1, row2.col2)` -> `convert(row1.col1, row1.col2) == convert(row2.col1, row2.col2)`

I ended up just separating the column data with pairs of nulls for the sake of "this is probably good enough for 99.99% of people", and not wanting to go full-on "let's build a database index" mode as I did a few years back:
https://github.com/josiahcarlson/yogatable/blob/master/lib/pack.py

I could probably make the exception read better, but not today ;)

**Comment by peter-conalgo** [comment]
Yup, your `identity_keygen` function works well. I think you should add that to the stock keygen functions, perhaps even as a default for string types. This issue has tripped me up quite a bit.

**Comment by josiahcarlson** [comment]
The identity keygen will be in rom 0.33.0 (to be released momentarily) as `IDENTITY` and `IDENTITY_CI` for case-sensitive and case-insensitive keygens, respectively.

**Comment by josiahcarlson** [comment]
Note that string columns do not have a default keygen.
