### ISSUE TITLE
Option for slow queries

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#74]
Of course we should all have indexes for things we query often. However, there are sometimes things that are not queried often, and so we shouldn't be building and updating an index for it all the time. But when it's time to walk the database for non-critical purposes (backup, debug, daily reports, etc), it seems like ROM could still help.

My example is the `path` column in #72... If I want a unique list of all paths, there is no way to express that using ROM. However, I think a `SORT` command could be constructed that returns the results fairly quickly.

Similarly, I might want to sort on a column occasionally, but not index it. `SORT` can do that... Or maybe count a value.

I'm not at all sure what the UI for this feature would look like, but at the end of the day it feels like a missing piece. In some ways, it's a mostly a wrapper for SORT, but there may be some cases where it can optimize based on what indexes you have already.

**Comment by josiahcarlson** [comment]
I will not be building arbitrary sorting on arbitrary columns. If you want order_by, build an index.

And no, `SORT` will not help here because there is no single set or list object that contains all entities. In fact, there are no lists being used at all, and the only way a set will be created with all entities is if you create the most boring index ever.
