### ISSUE TITLE
Would like to use UltraJSON in models.py

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#82]
I'd like to use UltraJSON for serializing Lua arguments (in `models.py`).

However, it does not support "default=" argument and there are no hooks given for replacing JSON library choice in this file or elsewhere in ROM.

In my case, this one file is using SimpleJSON (which got into my project as a requirement from some other component; not particularly wanted in this project) and the other files in ROM appear to be using standard-library JSON.

**Comment by josiahcarlson** [comment]
I removed the unnecessary simplejson part in 0.34.1. Really though, the built-in json library in 2.7 and 3.x is an out-dated simplejson library.

Ultra JSON does look to be substantially faster (about 2-5x faster for the benchmark I was doing), but its lack of validation and ability to handle non-standard Python types means that I can't be adding it as a requirement for rom, nor can I offer the option to users to use a custom JSON library as an option. Why? Because if a user says, "I want to use JSON library X", and that library breaks in some weird way when using rom, rom will be blamed. If you're looking for places where that might happen: http://mod16.org/hurfdurf/?p=266 , which was referenced in an issue in the UltraJSON Github, and was closed because they don't care about those things.

That said, *you* can certainly use UltraJSON with rom, and here's how you do it (in addition to the UltraJSON columns that you were using from before).

```
import json

import rom.model
import ujson

_loads = json.loads
_dumps = json.dumps

class myujson(object):
    @staticmethod
    def loads(data, **kwargs):
        try:
            return ujson.loads(data)
        except:
            return _loads(data, **kwargs)

    @staticmethod
    def dumps(data, **kwargs):
        try:
            return ujson.dumps(data)
        except:
            return _dumps(data, **kwargs)

rom.model.json = myujson()
```

For those objects/structures that would raise an exception, they get encoded/decoded properly. For those that wouldn't raise an exception, they pass through and are encoded/decoded fast (though the same issue with custom objects turning into `{}` remains - but that's UltraJSON).
