### ISSUE TITLE
Store file content on Model

### ISSUE THREAD

**Issue by Edorka** [josiahcarlson/rom#84]
I've been using ROM happily since months. Now we need to store binary files on our redis database but we get this error while saving:

`UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 16: invalid start byte`

this Model column is declared as 

`content = rom.String()`

It would be great to add binary data to out models. Thanks

**Comment by josiahcarlson** [comment]
You shouldn't be having any problems storing binary data with rom. Can you provide a complete example that shows the problem?

**Comment by Edorka** [comment]
sure, this is the declaration of the object:

    class BoardExcelJob(rom.Model):
        uuid = rom.String(required=True, unique=True)
        content = rom.String()
        created_at = rom.Float(default=time.time)

and this is the code that fails

        output = StringIO.StringIO()
        # Even though the final file will be in memory the module uses temp
        # files during assembly for efficiency. To avoid this on servers that
        # don't allow temp files, for example the Google APP Engine, set the
        # 'in_memory' constructor option to True:
        workbook = xlsxwriter.Workbook(output)
        worksheet = workbook.add_worksheet()
        # Write some test data.
        worksheet.write(0, 0, 'Hello, world!')
        # Close the workbook before streaming the data.
        workbook.close()
        # Rewind the buffer.
        output.seek(0)
        if not data.get('inmediate'):
            jobId = uuid.uuid4().hex
            stored = BoardExcelJob(
                uuid=jobId,
                content=output.read() 
            )
            stored.save()
            retrievalPath = url_for('exportboardexcel') + '/' + jobId
            return {'retrieveFrom': retrievalPath }

if I encode it to base64 the service works as expected.

    content=base64.b64encode( output.read() )

**Comment by josiahcarlson** [comment]
I'm finally getting a chance to look at this, and it will be solved in the next few hours. :)

**Comment by josiahcarlson** [comment]
Okay, good news and bad news.

The good news is: you already know how to fix it - use Base-64.

The bad news: to make my life easier, I had used json as a transport for structured data between rom and Redis, and use json as structured storage in Redis. Looking through the various StackOverflow examples of similar issues, I tried using all of the variations, and as far as I can tell... there is an incompatibility between how Python's json library handles binary vs. unicode data and how Redis' json library handles binary vs. unicode. I don't know which is right, all I know is that I can eliminate the exceptions, but then there is data corruption issues.

I could be wrong about this, and I'm going to leave this issue open so I can dig into it when it's not late Friday night.

**Comment by josiahcarlson** [comment]
Further investigation has lead me to discover the underlying issue.

When a binary string (str in 2.x, bytes in 3.x) is encoded to json, it must first turn into a unicode string to be properly encoded (the json spec is on unicode strings, not binary strings). After encoding, binary values like `\xc0` and `\x97` turn into `\u00c0` and `\u0097`. When the Lua script for saving decodes the json inside Redis, it sees the unicode characters, decodes them, and re-encodes them as utf-8, turning them into `\xc3\x80` and `\xc2\x97` for the above characters.

When rom pulls data from Redis, it gets the encoded version of the data (`\xc3\x80` and `\xc2\x97`), and thinks everything is just fine. But for binary strings, the data *sometimes* needs a trip through `.decode('utf-8').encode('latin-1')` in order to be fixed.

I believe I have correctly characterized the cases where strings read from Redis need to be fixed, and I have round-tripped the binary data from xlsxwriter that highlighted the issue. It's getting late tonight, but I hope to have a complete and tested version that fixes this tomorrow.

**Comment by josiahcarlson** [comment]
Released 0.35.0, which fixes this issue. Closing.

**Comment by Edorka** [comment]
Working like a charm. Thanks :+1:
