### ISSUE TITLE
Slow query with order_by on indexed column

### ISSUE THREAD

**Issue by yuvadm** [josiahcarlson/rom#92]
With the following model:

```python
class MyModel(rom.Model):
    timestamp = rom.DateTime(index=True)
    # ...
```

I'm getting these results:

```python
>>> MyModel.query.count()
1291150
>>> timeit.timeit("MyModel.query.order_by('-timestamp').limit(0, 10).execute()", number=1, setup="from foo import MyModel")
6.973913631998585
>>> timeit.timeit("MyModel.query.order_by('timestamp').limit(0, 10).execute()", number=1, setup="from foo import MyModel")
6.8010725649946835
>>> timeit.timeit("MyModel.query.limit(0, 10).execute()", number=1, setup="from foo import MyModel")
0.003274479000538122
```

Subsequent runs return similar results. Am I doing something wrong with the indexing and the order_by query?

**Comment by josiahcarlson** [comment]
Sorry for the late update here. No, you're not doing anything wrong with the query, it's just the way that indexes (and sorting) are implemented (mostly operations over Redis data structures). For indexes as they are built, you're best off limiting the number of results you want in some way via filtering, before sorting them - otherwise everything will be sorted (in Redis) prior to return.

Alternatively, if you want to perform queries more or less directly against indexes (without copies, intersects, etc.), the `model.get_by()` method lets you query for specific value ranges over existing indexes, and offers a hidden `_limit=(offset, count)` option for pagination. So `MyModel.get_by(timestamp=(start, end), _limit=(0, 1000))` to get the first 1000 items by ordered timestamp between the provided `start` and `end` time periods.
